id: E212_MNC
url: 'https://www.itu.int/pub/T-SP-E.212B'
title:
  en: >-
    Mobile Network Codes (MNC) for the international identification plan for
    public networks and subscriptions
  ru: >-
    Коды сетей подвижной связи (MNC) для плана международной идентификации для
    сетей общего пользования и абонентов
  zh: 用于公共网络和订户的国际识别规划的移动网络代码（MNC）
recommendation:
  body: ITU-T
  code: E.212
  version: 2016-09
