id: 1259
publication_date: 2023-01-01T16:11:43.176Z
cutoff_date: 2022-12-09T16:11:43.176Z
issn: 1564-5223
languages:
  en: true
authors:
  - address: |-
      Place des Nations CH-1211
      Genève 20 (Switzerland)
    contacts:
      - type: phone
        data: +41 22 730 5111
      - type: email
        data: itumail@itu.int
        recommended: true
  - name: Standardization Bureau (TSB)
    contacts:
      - type: phone
        data: +41 22 730 5211
        recommended: true
      - type: fax
        data: +41 22 730 5853
        recommended: true
      - type: email
        data: tsbmail@itu.int
        recommended: true
      - type: email
        data: tsbtson@itu.int
        recommended: true
  - name: Radiocommunication Bureau (BR)
    contacts:
      - type: phone
        data: +41 22 730 5560
        recommended: true
      - type: fax
        data: +41 22 730 5785
        recommended: true
      - type: email
        data: brmail@itu.int
        recommended: true
