id: T35_NA
title:
  en: >-
    List of the national authorities designated to assign ITU-T Recommendation
    T.35 terminal provider codes
url: 'https://www.itu.int/pub/T-SP-T.35B'
recommendation:
  body: ITU-T
  code: T.35
  version: 2000-02
