languages:
  en: true
authors:
  - address: |-
      Place des Nations CH-1211
      Genève 20 (Switzerland)
    contacts:
      - type: phone
        data: +41 22 730 5111
      - type: email
        data: itumail@itu.int
        recommended: true
  - name: Standardization Bureau (TSB)
    contacts:
      - type: phone
        data: +41 22 730 5211
        recommended: true
      - type: fax
        data: +41 22 730 5853
        recommended: true
      - type: email
        data: tsbmail@itu.int
        recommended: true
      - type: email
        data: tsbtson@itu.int
        recommended: true
  - name: Radiocommunication Bureau (BR)
    contacts:
      - type: phone
        data: +41 22 730 5560
        recommended: true
      - type: fax
        data: +41 22 730 5785
        recommended: true
      - type: email
        data: brmail@itu.int
        recommended: true
issn: 1564-5223
id: 964
cutoff_date: 2010-09-03T20:43:16.819Z
publication_date: 2010-09-15T20:43:16.819Z
