id: RR.25.1
title:
  en: >-
    Status of Radiocommunications between Amateur Stations of different
    Countries
     (in accordance with optional provision No. 25.1 of the Radio Regulations)
    and Form of Call Signs assigned by each Administration to its Amateur and
    Experimental Stations
url: 'https://www.itu.int/pub/T-SP-RR.25.1'
