id: T35_CC
title:
  en: >-
    List of Country or Geographical Area Codes for non standard facilities in
    telematic services
url: 'https://www.itu.int/pub/T-SP-T.35-2012'
recommendation:
  body: ITU-T
  code: T.35
  version: 2000-02
