id: R_SP_LN.VIII
title:
  en: List VIII - List of International Monitoring Stations
  ru: Список VIII – Список станций международного радиоконтроля
  zh: List VIII - List of International Monitoring Stations (zh)
url: 'https://www.itu.int/pub/R-SP-LN.VIII/'
