id: 1169
publication_date: 2019-04-01
cutoff_date: 2019-03-15
issn: 1564-5223
languages:
  en: yes
authors:
  - address: |-
      Place des Nations CH-1211
      Genève 20 (Switzerland)
    contacts:
      - type: phone
        data: +41 22 730 5111
      - type: email
        data: itumail@itu.int
        recommended: yes
  - name:
      en: Standardization Bureau (TSB)
      ru: Бюро стандартизации электросвязи (БСЭ)
      zh: 电信标准化局（TSB）
    contacts:
      - type: phone
        data: +41 22 730 5211
        recommended: yes
      - type: fax
        data: +41 22 730 5853
        recommended: yes
      - type: email
        data: tsbmail@itu.int
        recommended: yes
      - type: email
        data: tsbtson@itu.int
        recommended: yes
  - name:
      en: Radiocommunication Bureau (BR)
      ru: Бюро радиосвязи (БР)
      zh: 无线电通信局（BR）
    contacts:
      - type: phone
        data: +41 22 730 5560
        recommended: yes
      - type: fax
        data: +41 22 730 5785
        recommended: yes
      - type: email
        data: brmail@itu.int
        recommended: yes
