id: NNP
title:
  en: National Numbering Plan
  ru: Национальный план нумерации
  zh: 国内编号方案
url: 'http://www.itu.int/itu-t/inr/nnp/index.html'
recommendation:
  body: ITU-T
  code: E.129
  version: 2013-01
