name: deploy

on:
  push:
    branches: [ master, staging ]

jobs:
  trigger-deploy:
    name: Trigger deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build event type
        id: event_type
        run: |
          # workaround for https://github.com/ituob/itu-ob-data/issues/83
          BRANCH=${GITHUB_REF##*/}
          if [ "$BRANCH" = "master" ]; then
            echo "##[set-output name=value;]deploy_main"
          else
            echo "##[set-output name=value;]deploy_$BRANCH"
          fi
      - name: Trigger ituob.org
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ITUOB_CI_PAT_TOKEN }}
          repository: ituob/ituob.org
          event-type: ${{ steps.event_type.outputs.value }}
