name: deploy

on:
  push:
    branches: [ master ]

jobs:
  trigger-deploy:
    name: Trigger master deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build event type
        id: event_type
        run: |
          echo "##[set-output name=value;]deploy_${GITHUB_REF##*/}"
      - name: Trigger ituob.org
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ituob/ituob.org
          event-type: ${{ steps.event_type.outputs.value }}