name: deploy

on:
  push:
    branches: [ main, staging ]

jobs:
  trigger-deploy:
    name: Trigger deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build event type
        id: event_type
        run: |
          # workaround for https://github.com/ituob/itu-ob-data/issues/83
          BRANCH=${GITHUB_REF##*/}
          if [ "$BRANCH" = "main" ]; then
            echo "value=deploy_main" > $GITHUB_OUTPUT
          else
            echo "value=deploy_$BRANCH" > $GITHUB_OUTPUT
          fi

      - name: Trigger ituob.org
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ITUOB_CI_PAT_TOKEN }}
          repository: ituob/ituob.org
          event-type: ${{ steps.event_type.outputs.value }}
